### ISSUE TITLE
How to pass parameter in ensemble model?

### ISSUE THREAD

**Issue by GooVincent** [triton-inference-server/tensorrtllm_backend#71] opened 2023-11-01 02:47 UTC
As the normal procedure for tensorrtllm_backend is preprocessing -> (tensorrt_llm) process -> postprocessing. How to pass the customer parameter from the request, like request token length.

In my understanding, tensorrt_llm backend will finish the infer, it won't work to add input and output parameter. then the issue coming, in ensemble pipeline, how to pass the parameter from the preprocess module to poseprocess module. 

Please any way to solve this issue?

**Comment by byshiue** [comment] 2023-11-01 15:14
I think I don't really get your question. `max_tokens` ([here](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/ensemble/config.pbtxt#L37)) is a input form parameter, which is similar to `request token length`. Can you explain more for your question?

**Comment by GooVincent** [comment] 2023-11-02 02:52
Well, I understood how to pass the parameter from the model **preprocess** to model **tensorrt_llm**, like REQUEST_INPUT_LEN
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/85823463/5e566e06-1e03-4efb-96e1-a8faaacf2c8b)

but how to pass REQUEST_INPUT_LEN from model **tensorrt_llm** to the model **postprocess**, I get confused, as the output for tensorrt_llm should be fixed based the llm model. correct?

**Comment by byshiue** [comment] 2023-11-02 02:55
For ensemble, you should pass `REQUEST_INPUT_LEN` for `ensemble` to `postprocess`, instead of passing from `tensorrt_llm` to `postprocess`.

**Comment by GooVincent** [comment] 2023-11-02 03:19
Any guide for this please? as the REQUEST_INPUT_LEN is the intermediate result.

**Comment by byshiue** [comment] 2023-11-02 03:57
I get your point. As far as I know, there is no way to support such feature in tensorrt_llm backend directly because it needs to change the source code of batch_manager. You can try to map the output of preporcess to input of postprocess directly. I am not sure is it doable. You can ask in tritonserver repo.

**Comment by GooVincent** [comment] 2023-11-02 05:34
okay, thanks.

**Comment by GooVincent** [comment] 2023-11-02 08:23
> I get your point. As far as I know, there is no way to support such feature in tensorrt_llm backend directly because it needs to change the source code of batch_manager. You can try to map the output of preporcess to input of postprocess directly. I am not sure is it doable. You can ask in tritonserver repo.

Any way for the ensemble mode to know the request token length, as I wanna cut the original tokens.

**Comment by BasicCoder** [comment] 2023-11-03 14:24
> > I get your point. As far as I know, there is no way to support such feature in tensorrt_llm backend directly because it needs to change the source code of batch_manager. You can try to map the output of preporcess to input of postprocess directly. I am not sure is it doable. You can ask in tritonserver repo.
> 
> Any way for the ensemble mode to know the request token length, as I wanna cut the original tokens.

May be you can reference this https://github.com/triton-inference-server/tensorrtllm_backend/pull/95

**Comment by callmezhangchenchenokay** [comment] 2023-11-08 13:08
@GooVincent Hi ，
Have you solved it yet

**Comment by callmezhangchenchenokay** [comment] 2023-12-08 04:07
Here is a demo, you can pass out the REQUEST_INPUT_LEN in the middle, test ok

https://github.com/triton-inference-server/tensorrtllm_backend/blob/57de9f572f75f61fe17b668eea1430b030e1b721/all_models/inflight_batcher_llm/postprocessing/config.pbtxt

**Comment by byshiue** [comment] 2023-12-11 07:04
Since the issue is solved, close this bug. If you still have issue/question, feel free to ask and we will open the issue again.

**Closed by byshiue** 2023-12-11 07:04 UTC

**Comment by callmezhangchenchenokay** [comment] 2023-12-29 08:47
Sorry to interrupt again!

The solution mentioned above requires model_transaction_policy to be set to True,
Can only be used if stream = False,

However, this problem occurs when stream = True
<img width="1102" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/a216f237-b0f6-4217-a849-96040316f794">


So there needs to be a way to export REQUEST_INPUT_LEN from stream =True, model_transaction_policy =True

**Comment by byshiue** [comment] 2024-01-03 01:25
I don't get you point of "set model_transaction_policy to be True". `model_transaction_policy` is a set of policy and stream (decoupled mode) is one of them.

**Comment by callmezhangchenchenokay** [comment] 2024-01-04 03:29
Excuse me! It's my expression
What I'm trying to say is,

‘’‘
model_transaction_policy {
  decoupled: true
}
’‘’
(decoupled) If set to False, can export REQUEST_INPUT_LEN,
However, when decoupled is set to True, the following error is reported

<img width="1102" alt="293334648-a216f237-b0f6-4217-a849-96040316f794" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/562ab952-4903-4a4d-ab6a-101f612b808e">

**Comment by byshiue** [comment] 2024-01-08 03:57
> Excuse me! It's my expression What I'm trying to say is,
> 
> ‘’‘ model_transaction_policy { decoupled: true } ’‘’ (decoupled) If set to False, can export REQUEST_INPUT_LEN, However, when decoupled is set to True, the following error is reported
> 
> <img alt="293334648-a216f237-b0f6-4217-a849-96040316f794" width="1102" src="https://private-user-images.githubusercontent.com/146302419/294078155-562ab952-4903-4a4d-ab6a-101f612b808e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODYzMzMsIm5iZiI6MTcwNDY4NjAzMywicGF0aCI6Ii8xNDYzMDI0MTkvMjk0MDc4MTU1LTU2MmFiOTUyLTQ5MDMtNGE0ZC1hYjZhLTEwMWY2MTJiODA4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMzUzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmNlM2JmOWY3MDVjYjZjYzBlZjcxZmU4Y2EyMDFiZWM4MzU1MjRhMzNjOTc2MWI3ZTRlNmFkNzMxMzFiNjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vbOmqbL2xXSqNW36-1S81Zfc15opThTIy8xG5GzeW_A">

Could you try scripts here https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/llama.md#end-to-end-workflow-to-run-llama to run the streamming?
