### ISSUE TITLE
The Chinese output is garbled when enabled streaming for vicuna-13b

### ISSUE THREAD

**Issue by WeiboXu** [triton-inference-server/tensorrtllm_backend#192] opened 2023-12-06 07:55 UTC
In the TensorRT-LLM, when enable streaming, it will give the output from the first token to the end，when the last token is garbled, we can wait the next stream, the final output will be correct.
But after use Triton-tensorrtllm_backend, the output will be one by one token, when we concat the garbled token to the next one ,it still not correct, like below.

![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/40425866/376a90c5-4ab6-444d-84dc-a0a04e74dfc9)

Why there is such difference between TensorRT-LLM and Triton-tensorrtllm_backend?
In the file TensorRT-LLM/tensorrt_llm/runtime/generation.py
There is decode() function
if streaming:
    return self.decode_stream(...)
else:
    return self.decode_regular(...)

the output will be generate from the first token to the end.
Why for triton, it will generate one by one?
How to resolve such problem?

**Comment by byshiue** [comment] 2023-12-07 09:45
It may be because we cannot decode every id directly. Please try the tensorrt_llm_bls in latest codes.

**Comment by WeiboXu** [comment] 2023-12-14 09:49
tensorrt_llm_bls can resolve the English space  problem, but cannot resolve the Chinese show result, it is better than before, but it still exist garbled.
![1](https://github.com/triton-inference-server/tensorrtllm_backend/assets/40425866/64756c88-a87e-4348-bee3-1bb7672c7012)
![2](https://github.com/triton-inference-server/tensorrtllm_backend/assets/40425866/d8193274-467a-4f0f-b09c-fd98af544f0f)

**Comment by byshiue** [comment] 2023-12-16 16:04
In you middle example with chinese word, the second result and final result are reasonable. That means that when the tokenizer get the first token of answer 4, it generates strage word because it does not get enough tokens, and the tokenizer will continue improve the sentence when it receives more tokens. This behavior is expected and the issue is resolved.

**Comment by WeiboXu** [comment] 2023-12-18 07:36
Yes, the issue is resolved. Thanks.

**Comment by byshiue** [comment] 2023-12-18 13:42
Thank you for the update. Close this bug.

**Closed by byshiue** 2023-12-18 13:42 UTC
Labels: triaged

**Comment by Saigut** [comment] 2024-04-12 10:10
Hello, the output of tensorrt_llm_bls streaming mode is not one by one.

The output of tensorrt_llm_bls, like above:
```
I
I'
I'm 
I'm doing
I'm doing well
```

But the expected should be:
```
I
'
m 
 doing
 well
```

**Comment by byshiue** [comment] 2024-04-17 00:57
It is expected behavior because we detokenize all generated ids every time. Otherwise, some ids might map to one token and would lead to issue. 

For your feature request, you could postprocess that by something like `current_text - prev_text`.

**Comment by Saigut** [comment] 2024-04-17 08:53
> It is expected behavior because we detokenize all generated ids every time. Otherwise, some ids might map to one token and would lead to issue.
> 
> For your feature request, you could postprocess that by something like `current_text - prev_text`.

Got it. And there may be a more efficient way to cache tokens, like what [TextStreamer](https://github.com/huggingface/transformers/blob/5fabebdb7d4f9ee5a6459f7c0dcde0b1901f6205/src/transformers/generation/streamers.py#L99) does. 
TextStreamer will flush the token cache at appropriate times rather than always cache the whole tokens.

**Comment by byshiue** [comment] 2024-04-25 00:28
Thank yor for the suggestion, we will take a look.
