### ISSUE TITLE
ERROR: Failed to create instance: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq)

### ISSUE THREAD

**Issue by NarenZen** [triton-inference-server/tensorrtllm_backend#168] opened 2023-11-28 16:39 UTC
I referred this [official blog](https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/) to run the llama2 7b chat model

```
python3 tools/fill_template.py --in_place \
      all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt \
      decoupled_mode:true,engine_dir:/all_models/inflight_batcher_llm/tensorrt_llm/1,\
max_tokens_in_paged_kv_cache:,batch_scheduler_policy:guaranteed_completion,kv_cache_free_gpu_mem_fraction:0.2,\
max_num_sequences:4
 
python tools/fill_template.py --in_place \
    all_models/inflight_batcher_llm/preprocessing/config.pbtxt \
    tokenizer_type:llama,tokenizer_dir:meta-llama/Llama-2-7b-chat-hf
 
python tools/fill_template.py --in_place \
    all_models/inflight_batcher_llm/postprocessing/config.pbtxt \
    tokenizer_type:llama,tokenizer_dir:meta-llama/Llama-2-7b-chat-hf

docker run -it --rm --gpus all --network host --shm-size=1g \
-v $(pwd)/all_models:/all_models \
-v $(pwd)/scripts:/opt/scripts \
nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3
 
# Log in to huggingface-cli to get tokenizer
huggingface-cli login --token *****
 
# Install python dependencies
pip install sentencepiece protobuf
```

when i ran the final command 
`python /opt/scripts/launch_triton_server.py --model_repo /all_models/inflight_batcher_llm --world_size 1`

I'm getting the below error

```
[TensorRT-LLM][INFO] Using 693 tokens in paged KV cache.
E1128 16:31:49.479096 227 backend_model.cc:634] ERROR: Failed to create instance: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq)
E1128 16:31:49.479182 227 model_lifecycle.cc:621] failed to load 'tensorrt_llm' version 1: Internal: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq)
I1128 16:31:49.479201 227 model_lifecycle.cc:756] failed to load 'tensorrt_llm'
E1128 16:31:49.479285 227 model_repository_manager.cc:563] Invalid argument: ensemble 'ensemble' depends on 'tensorrt_llm' which has no loaded version. Model 'tensorrt_llm' loading failed with error: version 1 is at UNAVAILABLE state: Internal: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq);
I1128 16:31:49.479354 227 server.cc:592]
```

**Comment by byshiue** [comment] 2023-11-29 07:48
You can try setting larger `kv_cache_free_gpu_mem_fraction` or `max_tokens_in_paged_kv_cache`. 

Or try using smaller beam_width or input_len/output_len when you build engine.

**Comment by byshiue** [comment] 2023-11-29 09:39
When you setup `kv_cache_free_gpu_mem_fraction` and `max_tokens_in_paged_kv_cache`, TRT LLM will choose smaller than and I guess `max_tokens_in_paged_kv_cache:500` is not enough. Could you try only setting `kv_cache_free_gpu_mem_fraction` first.

**Comment by NarenZen** [comment] 2023-11-29 09:48
I also tried just setting the kv_cache_free_gpu_mem_fraction :1 
But no luck

**Comment by NarenZen** [comment] 2023-11-29 10:11
working.

fill_template.py is not update the values if running for second time.
I changed the kv_cache_free_gpu_mem_fraction :0.8 in the config file directly.

Changing directly in config.pbtxt fixed the issue

**Comment by byshiue** [comment] 2023-11-30 09:26
Thanks for updating. Close this bug as it is solved. Feel free to reopen it if needed.

**Closed by byshiue** 2023-11-30 09:26 UTC
Labels: triaged

**Comment by sleepwalker2017** [comment] 2023-12-04 08:46
> Thanks for updating. Close this bug as it is solved. Feel free to reopen it if needed.

how is it solved? in which commit or pr?

**Comment by caseylai** [comment] 2023-12-21 08:51
Same error when launching baichuan 1 13B model. I tried to change the value of maxTokensInPagedKvCache in config file to a large number (100000000) but still failed. (beam width is 1, tokens per block is 64, not found the value of max blocks per seq)

**Comment by byshiue** [comment] 2023-12-25 08:39
There is no bug. The issue is caused by wrong settings. When you setup `maxTokensInPagedKvCache` and `kv_cache_free_gpu_mem_fraction`, trt llm will choose smaller one automatically. So, you need to check you set both number well or only setup one of them.

**Comment by amir1m** [comment] 2024-01-20 10:41
Hi @byshiue, @NarenZen ,
I understand this is a config issue however I am getting the same error  with on 2x A10 GPU machine with total 48GB. Is it supposed to work on A10/this configuration?

```
[TensorRT-LLM][INFO] Allocate 872415232 bytes for k/v cache. 
[TensorRT-LLM][INFO] Using 1664 total tokens in paged KV cache, and 20 blocks per sequence
E0120 10:37:25.134537 24459 backend_model.cc:635] ERROR: Failed to create instance: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache (1664) must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width (1) * tokensPerBlock (128) * maxBlocksPerSeq (20))
```

My configuration from `tensorrt_llm/config.pbtxt`
- kv_cache_free_gpu_mem_fraction : 0.9
- max_tokens_in_paged_kv_cache : Commented out as I understand only one is sufficient.
- max_attention_window_size:2560
- max_batch_size: 8
- decoupled: True
- batch_scheduler_policy:guaranteed_completion
- gpt_model_type:inflight_fused_batching
- max_num_sequences:1

Could you please help if I am missing something here?

Thanks.

**Comment by 0xMatthew** [comment] 2024-02-14 05:39
@amir1m, I'm having the same issue. Granted, I'm doing this on a measly 3080 10GB, but I can't get inference working with Triton. I can run the model without issue using the run.py script provided with TensorRT-LLM, but I keep getting the `[TensorRT-LLM][INFO] Allocate 872415232 bytes for k/v cache. 
[TensorRT-LLM][INFO] Using 1664 total tokens in paged KV cache, and 20 blocks per sequence
E0120 10:37:25.134537 24459 backend_model.cc:635] ERROR: Failed to create instance: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache (1664) must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width (1) * tokensPerBlock (128) * maxBlocksPerSeq (20))` you're getting.

Did you ever figure out what you problem was?

**Comment by hillarysanders** [comment] 2024-02-14 21:06
python3 tools/fill_template.py is using string.Template.safe_substitute to replace values, meaning that only a value represented as "$foo" in the configuration file will be replaced.

Seems to me that in the case of `./all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt`, it looks to me that everything is hardcoded except the single parameter ${enable_trt_overlap}. If you try to override anything but that, the override is just silently ignored.

That seems *bad* - is that really what is wanted? Or am I misunderstanding something big?

**Comment by 0xMatthew** [comment] 2024-02-16 22:30
> `python3 tools/fill_template.py` is using string.Template.safe_substitute to replace values, meaning that only a value represented as "$foo" in the configuration file will be replaced.
> 
> Seems to me that once you use fill_template.py once, everything you specified becomes hardcoded. If you try to override anything later using `python3 tools/fill_template.py --in_place`, the override is just **silently** ignored.
> 
> That seems _bad_ - is that really what is wanted? Or am I misunderstanding something big?

you're correct. the script isn't very robust, but it gets the job done (assuming you configure things right the first time and/or backed up your original config files).

in the devs' defense, i believe there are a lot of moving parts in this space, and we are working with the early stages of TensorRT-LLM and should adjust our expectations as such.

FWIW, i've spent many hours configuring environments with Triton/TensorRT-LLM. i've run into a countless little issues, even if you faithfully follow the TensorRT-LLM documentation. there are many contradictions in the documentation, things that are out of date, pointers to things that are no longer relevant, etc. etc.

i assume NVIDIA will refine the documentation for TensorRT-LLM as their product matures. there are real performance gains to using TensorRT-LLM as a model backend, and businesses everywhere are scrambling to add LLM inference to their software offerings. i have to imagine there will be a lot more adoption soon. in my experience, it is the squeaky wheel gets that gets the grease. when more companies are looking to efficiently leverage their hardware, they'll use TensorRT-LLM+Triton.

**Comment by LeonBinder** [comment] 2024-12-13 08:31
Did someone ever figure it out? Currently facing the same issue
