### ISSUE TITLE
[Question] Any plan to support mixtral or other MoE model?

### ISSUE THREAD

**Issue by kisseternity** [triton-inference-server/tensorrtllm_backend#342] opened 2024-02-20 04:05 UTC
Hello, tensorrt_llm project has already supported mixtral model, is there plan for tensorrtllm_backend to support this model? Thanks.

**Comment by byshiue** [comment] 2024-02-27 03:44
Have you tried running Mixtral on backend? If not, please take a try.

**Comment by kisseternity** [comment] 2024-02-27 03:54
> Have you tried running Mixtral on backend? If not, please take a try.

Yes I've tried. The triton_llm version which supports Mixtral is pretty new so that probably tensorrtllm_backend may not be compatible. After modifying the generated configure files, still some errors occur. Not sure if the module name in Mixtral model not defined in tensorrtllm_backend causing this error.

**Comment by TallaKuate** [comment] 2024-02-27 05:43
Here is an error message: 

`[TRT-LLM] [I] Loading HF LLaMA ... from /Mixtral-8x7B-v0.1/
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 906, in <module>
    build(0, args)
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 850, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 678, in build_rank_engine
    hf_llama = hf_model.from_pretrained(
AttributeError: 'NoneType' object has no attribute 'from_pretrained'`



The build command is the following 

"python3 /tensorrtllm_backend/tensorrt_llm/examples/llama/build.py --model_dir /Mixtral-8x7B-v0.1/ \
                --use_inflight_batching \
                --enable_context_fmha \
                --use_gemm_plugin \
                --world_size 4 \
                --pp_size 4 \
                --output_dir /engines/4-gpu/"

**Comment by djns99** [comment] 2024-03-01 00:11
Hi @kisseternity versions after v0.7.1 tensorrtllm_backend should support Mixtral, however if you are having issues I would recommend trying the new [v0.8.0](https://github.com/triton-inference-server/tensorrtllm_backend/releases/tag/v0.8.0) version released today. 

@TallaKuate that error is likely caused by an out of date transformer version. See examples/mixtral/requirements.txt for the correct version. I would also recommend updating to v0.8.0 as that should install the correct version by default

**Comment by TallaKuate** [comment] 2024-03-06 09:03
Hey, 
My issue has been resolved with the version v0.8.0. 
Thanks

**Comment by byshiue** [comment] 2024-03-13 06:32
Close this issue because the model is supported.

**Closed by byshiue** 2024-03-13 06:32 UTC
Labels: triaged
